import math
import os
import random
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from MDR import Exam, Question, load

import numpy as np

import qliff
from qliff import Circuit, PauliString, Simulator, fidelity
from qliff._core import ColTableau
from qliff.noise import BitFlip
from qliff.pauli import canonicalize, parse_signed
from qliff.simulator import GATE_OPCODE


def _teleport(prepare, seed):
    """
    Teleport a state prepared on q0 through a Bell pair (q1, q2) onto q2.
    """
    sim = Simulator(3, seed=seed)
    prepare(sim)
    sim.H(1).CX(1, 2)
    sim.CX(0, 1).H(0)
    if sim.M(1) == 1:
        sim.X(2)
    if sim.M(0) == 1:
        sim.Z(2)

    return sim


class Smoke(Question):
    def test_import(self):
        """
        `import qliff` succeeds and exposes a version.
        """
        self.assertTrue(
            hasattr(qliff, "__version__"), msg="qliff must expose __version__"
        )

    def test_version(self):
        """
        Version is sourced from the Rust crate and equals 1.0.0.
        """
        self.assertEqual(qliff.__version__, "1.0.0", msg="version must be 1.0.0")


class TableauTests(Question):
    def _grp(self, sim, *gens):
        """
        Assert the simulator's stabilizer group equals the one generated by gens.
        """
        exp = canonicalize([parse_signed(g) for g in gens], sim.num_qubits)

        self.assertEqual(sim.canon(), exp, msg="stabilizer group mismatch")

    def test_zero_1q(self):
        """
        |0> is stabilized by +Z.
        """
        self._grp(Simulator(1), "+Z")

    def test_zero_3q(self):
        """
        |000> is stabilized by +ZII, +IZI, +IIZ.
        """
        self._grp(Simulator(3), "+ZII", "+IZI", "+IIZ")

    def test_h_plus(self):
        """
        H|0> = |+>, stabilized by +X.
        """
        s = Simulator(1).H(0)
        self._grp(s, "+X")

    def test_s_maps_x_to_y(self):
        """
        S maps X -> Y.
        """
        s = Simulator(1).H(0).S(0)
        self._grp(s, "+Y")

    def test_z_makes_minus(self):
        """
        Z|+> = |->, stabilized by -X.
        """
        s = Simulator(1).H(0).Z(0)
        self._grp(s, "-X")

    def test_y_gate(self):
        """
        Y|0> = i|1>, stabilized by -Z.
        """
        s = Simulator(1).Y(0)
        self._grp(s, "-Z")

    def test_s_dag_inverts_s(self):
        """
        S_DAG . S = identity.
        """
        s = Simulator(1).H(0).S(0).S_DAG(0)
        self._grp(s, "+X")

    def test_bell(self):
        """
        Bell state stabilizers +XX, +ZZ.
        """
        s = Simulator(2).H(0).CX(0, 1)
        self._grp(s, "+XX", "+ZZ")

    def test_ghz(self):
        """
        GHZ_3 group generated by XXX, ZZI, IZZ.
        """
        s = Simulator(3).H(0).CX(0, 1).CX(0, 2)
        self._grp(s, "+XXX", "+ZZI", "+IZZ")

    def test_cz_on_plus(self):
        """
        CZ|++> stabilized by XZ, ZX.
        """
        s = Simulator(2).H(0).H(1).CZ(0, 1)
        self._grp(s, "+XZ", "+ZX")

    def test_swap(self):
        """
        SWAP exchanges |+>|0> -> |0>|+>.
        """
        s = Simulator(2).H(0).SWAP(0, 1)
        self._grp(s, "+ZI", "+IX")

    def test_cx_varargs_pairs(self):
        """
        CX accepts flattened (control, target) pairs.
        """
        s = Simulator(3).H(0).CX(0, 1, 1, 2)  # GHZ via a chain
        self._grp(s, "+XXX", "+ZZI", "+IZZ")

    def test_random_clifford_inverse(self):
        """
        A random Clifford followed by its inverse returns to |0...0>.
        """
        rng = random.Random(7)
        n = 6
        s = Simulator(n)
        ops = []
        for _ in range(120):
            k = rng.random()
            if k < 0.34:
                q = rng.randrange(n)
                s.H(q)
                ops.append(("H", q))
            elif k < 0.67:
                q = rng.randrange(n)
                s.S(q)
                ops.append(("S", q))
            else:
                a = rng.randrange(n)
                b = rng.randrange(n)
                while b == a:
                    b = rng.randrange(n)
                s.CX(a, b)
                ops.append(("CX", a, b))
        for op in reversed(ops):
            if op[0] == "H":
                s.H(op[1])
            elif op[0] == "S":
                s.S_DAG(op[1])
            else:
                s.CX(op[1], op[2])  # CX is its own inverse
        zero = ["+" + "I" * i + "Z" + "I" * (n - 1 - i) for i in range(n)]
        self._grp(s, *zero)


class StandardTests(Question):
    def test_bell_stabilizers(self):
        """
        The Bell state H(0).CX(0,1) has canonical stabilizers +XX, +ZZ.
        """
        sim = Simulator(2).H(0).CX(0, 1)

        self.assertEqual(sim.canon(), ["+XX", "+ZZ"], msg="Bell stabilizers")

    def test_bell_correlation(self):
        """
        Measuring both Bell qubits yields equal outcomes across many seeds.
        """
        for seed in range(200):
            sim = Simulator(2, seed=seed).H(0).CX(0, 1)
            m0 = sim.M(0)
            m1 = sim.M(1)

            self.assertEqual(m0, m1, msg=f"Bell outcomes must agree (seed {seed})")

    def test_ghz_stabilizers(self):
        """
        GHZ on 4 qubits via H + CX chain has the expected canonical stabilizers.
        """
        sim = Simulator(4).H(0).CX(0, 1, 1, 2, 2, 3)
        expected = ["+XXXX", "+ZIIZ", "+IZIZ", "+IIZZ"]

        self.assertEqual(sim.canon(), expected, msg="GHZ4 stabilizers")

    def test_ghz_correlation(self):
        """
        GHZ all-Z measurements collapse to either all-zero or all-one.
        """
        for seed in range(150):
            sim = Simulator(4, seed=seed).H(0).CX(0, 1, 1, 2, 2, 3)
            outs = sim.M(0, 1, 2, 3)

            self.assertEqual(
                len(set(outs)), 1, msg=f"GHZ outcomes must all agree (seed {seed})"
            )

    def test_teleport_plus(self):
        """
        Teleporting |+> gives <X> = +1 on the output qubit q2.
        """
        for seed in range(12):
            sim = _teleport(lambda s: s.H(0), seed)

            self.assertEqual(
                sim.peek("IIX"), 1, msg=f"|+> teleported <X> (seed {seed})"
            )

    def test_teleport_minus(self):
        """
        Teleporting |-> gives <X> = -1 on the output qubit q2.
        """
        for seed in range(12):
            sim = _teleport(lambda s: s.H(0).Z(0), seed)

            self.assertEqual(
                sim.peek("IIX"), -1, msg=f"|-> teleported <X> (seed {seed})"
            )

    def test_teleport_zero(self):
        """
        Teleporting |0> gives <Z> = +1 on the output qubit q2.
        """
        for seed in range(12):
            sim = _teleport(lambda s: s, seed)

            self.assertEqual(
                sim.peek("IIZ"), 1, msg=f"|0> teleported <Z> (seed {seed})"
            )

    def test_teleport_one(self):
        """
        Teleporting |1> gives <Z> = -1 on the output qubit q2.
        """
        for seed in range(12):
            sim = _teleport(lambda s: s.X(0), seed)

            self.assertEqual(
                sim.peek("IIZ"), -1, msg=f"|1> teleported <Z> (seed {seed})"
            )

    def test_reset_to_zero(self):
        """
        R resets a qubit to |0>, so <Z> = +1 afterward.
        """
        sim = Simulator(1).X(0)
        sim.R(0)

        self.assertEqual(sim.peek("Z"), 1, msg="R must reset to |0>")

    def test_measure_reset(self):
        """
        MR measures the prior value then leaves the qubit in |0>.
        """
        sim = Simulator(1).X(0)
        out = sim.MR(0)

        self.assertEqual(out, 1, msg="MR must report the pre-reset value")

        self.assertEqual(sim.peek("Z"), 1, msg="MR must reset to |0>")

    def test_measure_then_reuse(self):
        """
        A qubit measured and reset can be re-prepared and remeasured.
        """
        sim = Simulator(1, seed=0).H(0)
        sim.MR(0)
        sim.X(0)

        self.assertEqual(sim.M(0), 1, msg="reused qubit must measure 1 after X")

    def test_stabilizer_deterministic(self):
        """
        On a Bell state, measure of ZZ and XX is a deterministic +1.
        """
        sim = Simulator(2).H(0).CX(0, 1)
        zz, zz_random = sim.measure("ZZ")
        xx, xx_random = sim.measure("XX")

        self.assertEqual(zz, 1, msg="Bell ZZ must be +1")

        self.assertFalse(zz_random, msg="Bell ZZ must be deterministic")

        self.assertEqual(xx, 1, msg="Bell XX must be +1")

        self.assertFalse(xx_random, msg="Bell XX must be deterministic")

    def test_stabilizer_random(self):
        """
        On a product state |00>, measuring XX is a random coin flip.
        """
        sim = Simulator(2, seed=0)
        _value, random = sim.measure("XX")

        self.assertTrue(random, msg="XX on |00> must be random")

    def test_noisy_flip_rate(self):
        """
        X_ERROR(p) flips |0> with empirical frequency close to p.
        """
        c = Circuit(1)
        c.X_ERROR(0, 0.25)
        c.M(0)
        recs = c.sample(5000, seed=2)
        rate = recs[:, 0].mean()

        self.assertLess(abs(rate - 0.25), 0.03, msg=f"flip rate {rate:.3f} != 0.25")

    def test_depolarize_flip_rate(self):
        """
        DEPOLARIZE1(0.75) on |0> gives a measured-one frequency near 0.5.
        """
        c = Circuit(1)
        c.DEPOLARIZE1(0, 0.75)
        c.M(0)
        recs = c.sample(5000, seed=3)
        rate = recs[:, 0].mean()

        self.assertLess(abs(rate - 0.5), 0.04, msg=f"depolarized {rate:.3f} != 0.5")

    def test_coherent_estimate(self):
        """
        For H(0).RZ(0, theta), estimate of <X> tracks cos(theta).
        """
        for theta in (0.0, math.pi / 4, math.pi / 2, math.pi):
            c = Circuit(1)
            c.H(0)
            c.RZ(0, theta)
            got = c.estimate("X", shots=5000, seed=7)
            want = math.cos(theta)

            self.assertLess(
                abs(got - want),
                0.05,
                msg=f"<X> for RZ({theta:.2f}): got {got:.3f} want {want:.3f}",
            )

    def test_fidelity_identical(self):
        """
        Two identical Bell states have fidelity 1.0.
        """
        a = Simulator(2).H(0).CX(0, 1)
        b = Simulator(2).H(0).CX(0, 1)

        self.assertEqual(fidelity(a, b), 1.0, msg="identical states fidelity 1")

    def test_fidelity_orthogonal(self):
        """
        Orthogonal |Phi+> and |Phi-> have fidelity 0.0.
        """
        phi_plus = Simulator(2).H(0).CX(0, 1)
        phi_minus = Simulator(2).X(0).H(0).CX(0, 1)

        self.assertEqual(
            fidelity(phi_plus, phi_minus), 0.0, msg="orthogonal fidelity 0"
        )

    def test_fidelity_half(self):
        """
        |0> and |+> overlap with fidelity 0.5.
        """
        zero = Simulator(1)
        plus = Simulator(1).H(0)

        self.assertEqual(fidelity(zero, plus), 0.5, msg="|0> vs |+> fidelity 0.5")


class MeasureTests(Question):
    def test_zero_deterministic(self):
        """
        Measuring |000> gives 0 on every qubit.
        """
        self.assertEqual(
            Simulator(3).M(0, 1, 2), [0, 0, 0], msg="|000> must measure all zero"
        )

    def test_x_gives_one(self):
        """
        X|0> measures 1.
        """
        self.assertEqual(Simulator(1).X(0).M(0), 1, msg="X|0> must measure 1")

    def test_repeatable(self):
        """
        Measuring the same qubit twice agrees.
        """
        s = Simulator(1).H(0)

        self.assertEqual(s.M(0), s.M(0), msg="repeated measurement must agree")

    def test_bell_correlation(self):
        """
        Bell-pair outcomes are perfectly correlated.
        """
        for seed in range(200):
            s = Simulator(2, seed=seed).H(0).CX(0, 1)

            self.assertEqual(s.M(0), s.M(1), msg="Bell outcomes must correlate")

    def test_plus_statistics(self):
        """

        |+> measures 0/1 about 50:50.
        """
        outs = [Simulator(1, seed=i).H(0).M(0) for i in range(4000)]

        self.samplesClose(
            outs,
            {
                0: 0.5,
                1: 0.5,
            },
            atol=0.04,
            msg="|+> should measure 0/1 evenly",
        )

    def test_ghz_statistics(self):
        """
        GHZ_3 collapses only to 000 or 111, about 50:50.
        """
        c = Counter()
        n = 3000
        for i in range(n):
            s = Simulator(3, seed=i).H(0).CX(0, 1).CX(0, 2)
            c[tuple(s.M(0, 1, 2))] += 1

        self.assertEqual(
            set(c) - {(0, 0, 0), (1, 1, 1)},
            set(),
            msg="GHZ must collapse only to 000 or 111",
        )

        self.assertLess(
            abs(c[(0, 0, 0)] / n - 0.5), 0.05, msg="000 share should be near 50%"
        )

    def test_record(self):
        """
        Measurements append to the record in order.
        """
        s = Simulator(2).X(0)
        s.M(0)
        s.M(1)

        self.assertEqual(s.record, [1, 0], msg="record must reflect measurement order")


class ExpectationTests(Question):
    def test_z_on_zero(self):
        """
        <Z> = +1 on |0>.
        """
        self.assertEqual(Simulator(1).peek("Z"), 1, msg="<Z> on |0> must be +1")

    def test_z_on_one(self):
        """
        <Z> = -1 on |1>.
        """
        self.assertEqual(Simulator(1).X(0).peek("Z"), -1, msg="<Z> on |1> must be -1")

    def test_x_on_plus(self):
        """
        <X> = +1 on |+>.
        """
        self.assertEqual(Simulator(1).H(0).peek("X"), 1, msg="<X> on |+> must be +1")

    def test_x_on_minus(self):
        """
        <X> = -1 on |->.
        """
        self.assertEqual(
            Simulator(1).H(0).Z(0).peek("X"), -1, msg="<X> on |-> must be -1"
        )

    def test_z_on_plus_is_zero(self):
        """
        <Z> = 0 on |+> (anticommutes with the stabilizer).
        """
        self.assertEqual(Simulator(1).H(0).peek("Z"), 0, msg="<Z> on |+> must be 0")

    def test_bell_observables(self):
        """
        Bell state: <ZZ>=<XX>=+1, <YY>=-1, <ZI>=0.
        """
        s = Simulator(2).H(0).CX(0, 1)

        self.assertEqual(s.peek("ZZ"), 1, msg="Bell <ZZ> must be +1")

        self.assertEqual(s.peek("XX"), 1, msg="Bell <XX> must be +1")

        self.assertEqual(s.peek("YY"), -1, msg="Bell <YY> must be -1")

        self.assertEqual(s.peek("ZI"), 0, msg="Bell <ZI> must be 0")

    def test_signed_observable(self):
        """
        A '-' prefix flips the expectation.
        """
        self.assertEqual(Simulator(1).peek("-Z"), -1, msg="'-' prefix must flip <Z>")

    def test_pauli_string_arg(self):
        """
        peek accepts a PauliString.
        """
        s = Simulator(2).H(0).CX(0, 1)

        self.assertEqual(
            s.peek(PauliString.parse("ZZ")),
            1,
            msg="PauliString arg must give <ZZ>=+1",
        )


class PauliTests(Question):
    def test_parse_repr_roundtrip(self):
        """
        Parsing then repr is the identity for signed Paulis.
        """
        for s in ("+XZ", "-Y", "+III", "-XYZ"):
            self.assertEqual(
                repr(PauliString.parse(s)), s, msg="parse/repr must round-trip"
            )

    def test_identity(self):
        """
        identity(n) is +I...I.
        """
        self.assertEqual(
            repr(PauliString.identity(3)), "+III", msg="identity(3) must be +III"
        )

    def test_from_sparse(self):
        """
        from_sparse places single-qubit Paulis.
        """
        self.assertEqual(
            repr(
                PauliString.from_sparse(
                    3,
                    {
                        0: "X",
                        2: "Z",
                    },
                )
            ),
            "+XIZ",
            msg="from_sparse must place X and Z",
        )

    def test_commutation(self):
        """
        X and Z anticommute; XX and ZZ commute.
        """
        self.assertFalse(
            PauliString.parse("X").commutes_with(PauliString.parse("Z")),
            msg="X and Z must anticommute",
        )

        self.assertTrue(
            PauliString.parse("XX").commutes_with(PauliString.parse("ZZ")),
            msg="XX and ZZ must commute",
        )

    def test_mul_xy_is_iz(self):
        """
        X * Y = +iZ.
        """
        self.assertEqual(
            repr(PauliString.parse("X") * PauliString.parse("Y")),
            "+iZ",
            msg="X * Y must be +iZ",
        )

    def test_mul_yx_is_minus_iz(self):
        """
        Y * X = -iZ.
        """
        self.assertEqual(
            repr(PauliString.parse("Y") * PauliString.parse("X")),
            "-iZ",
            msg="Y * X must be -iZ",
        )

    def test_mul_zz_is_identity(self):
        """
        Z * Z = +I.
        """
        self.assertEqual(
            repr(PauliString.parse("Z") * PauliString.parse("Z")),
            "+I",
            msg="Z * Z must be +I",
        )

    def test_mul_signs(self):
        """
        (-X)*(Y) carries the - through: = -iZ.
        """
        self.assertEqual(
            repr(PauliString.parse("-X") * PauliString.parse("Y")),
            "-iZ",
            msg="(-X) * Y must be -iZ",
        )


class CircuitTests(Question):
    def test_bell_matches_direct(self):
        """
        A Bell circuit reproduces the directly-built Bell state.
        """
        c = Circuit().append("H", 0).append("CX", [0, 1])
        got = c.run(seed=1).canon()
        want = Simulator(2).H(0).CX(0, 1).canon()

        self.assertEqual(got, want, msg="circuit Bell must match direct Bell")

    def test_fluent_matches_append(self):
        """
        Fluent gate methods build the same instructions as append.
        """
        fluent = Circuit(2).H(0).CX(0, 1).M(0, 1)
        low = Circuit(2).append("H", 0).append("CX", [0, 1]).append("M", [0, 1])

        self.assertEqual(
            fluent.instructions, low.instructions, msg="fluent must equal append"
        )

    def test_custom_channel_round_trips(self):
        """
        A custom Channel added via noise() is sampled like a built-in one.
        """
        c = Circuit(1).X(0).noise(BitFlip(1.0), 0).M(0)
        record = c.sample(1, seed=0)[0]

        self.assertEqual(record.tolist(), [0], msg="certain bit-flip must undo the X")

    def test_is_pauli_and_estimate(self):
        """
        is_pauli flags coherent noise and estimate stays unbiased for it.
        """
        pauli = Circuit(1).H(0).DEPOLARIZE1(0, 0.1)

        self.assertTrue(pauli.is_pauli, msg="depolarizing is a Pauli channel")

        coherent = Circuit(1).H(0).RZ(0, 0.0)

        self.assertFalse(coherent.is_pauli, msg="RZ is not a Pauli channel")

        est = coherent.estimate("X", 4000, seed=0)

        self.assertGreater(est, 0.9, msg="RZ(0) leaves <X> at +1")

    def test_measurements_recorded(self):
        """
        Measurement instructions populate the record in order.
        """
        c = Circuit().append("X", 0).append("M", [0, 1])

        self.assertEqual(
            c.run().record, [1, 0], msg="measurements must record in order"
        )

    def test_reproducible_with_seed(self):
        """
        The same seed gives the same measurement record.
        """
        c = Circuit(2).append("H", 0).append("CX", [0, 1]).append("M", [0, 1])

        self.assertEqual(
            c.run(seed=42).record,
            c.run(seed=42).record,
            msg="same seed must reproduce the record",
        )

    def test_infers_num_qubits(self):
        """
        num_qubits grows to cover the targets used.
        """
        c = Circuit().append("H", 0).append("CX", [0, 3])

        self.assertEqual(c.num_qubits, 4, msg="num_qubits must cover target index 3")

    def test_len_and_repr(self):
        """
        len and repr reflect the instruction list.
        """
        c = Circuit().append("H", 0).append("CX", [0, 1])

        self.assertEqual(len(c), 2, msg="len must equal instruction count")

        self.assertIn("Circuit", repr(c), msg="repr must mention Circuit")

    def test_unknown_instruction_raises(self):
        """
        Noise/QEC instructions are not runnable by the bare runner yet.
        """
        c = Circuit(1).append("DEPOLARIZE1", [0], 0.1)
        with self.assertRaises(NotImplementedError):
            c.run()


# opcodes for the raw ColTableau batch instruction stream (see ColTableau::run)
_X = GATE_OPCODE["X"]
_H = GATE_OPCODE["H"]
_CX = GATE_OPCODE["CX"]


class BatchSamplerTests(Question):
    """
    The deferred-transpose batch sampler (ColTableau.sample_batch /
    sample_batch_signed): consecutive measurements share one col<->row transpose,
    flushed only when a gate touches a buffered qubit. These lock the pure-
    optimisation guarantee -- deferring must not change any recorded bit.
    """

    def test_deferred_collision_flushes_before_gate(self):
        """
        A gate on a qubit with a buffered measurement flushes it first: X;MR resets
        the qubit, so the following CX sees |0> and cannot flip its target.
        """
        # X(0); MR(0)=1 (resets 0 to |0>); CX(0,1) (0 is |0> -> no-op); M(0); M(1)
        instrs = [
            (0, _X, 0, 0),
            (1, 1, 0, 0),
            (0, _CX, 0, 1),
            (1, 0, 0, 0),
            (1, 0, 1, 0),
        ]
        core = ColTableau(2)
        buf, num_meas = core.sample_batch(instrs, [], 16, 0)
        rows = np.frombuffer(buf, dtype=np.uint8).reshape(16, num_meas)

        self.assertEqual(num_meas, 3, msg="MR + two M -> three records")

        for row in rows:
            self.assertEqual(
                row.tolist(), [1, 0, 0], msg="collision flush must reset before the CX"
            )

    def test_deferred_measurements_held_across_gate(self):
        """
        Measurements on other qubits stay buffered across a non-touching gate and
        flush in call order, giving the exact record the eager order would.
        """
        # X(0); X(1); MR(0)=1; MR(1)=1; H(2);H(2)=I (buffer survives); M(0);M(1);M(2)
        instrs = [
            (0, _X, 0, 0),
            (0, _X, 1, 0),
            (1, 1, 0, 0),
            (1, 1, 1, 0),
            (0, _H, 2, 0),
            (0, _H, 2, 0),
            (1, 0, 0, 0),
            (1, 0, 1, 0),
            (1, 0, 2, 0),
        ]
        core = ColTableau(3)
        buf, num_meas = core.sample_batch(instrs, [], 8, 123)
        rows = np.frombuffer(buf, dtype=np.uint8).reshape(8, num_meas)

        for row in rows:
            self.assertEqual(
                row.tolist(),
                [1, 1, 0, 0, 0],
                msg="buffered MRs must reset before the trailing M reads them",
            )

    def test_sample_batch_reproducible(self):
        """
        The batched sampler is deterministic in its seed: identical bytes twice.
        """
        instrs = [
            (0, _H, 0, 0),
            (0, _CX, 0, 1),
            (1, 1, 0, 0),
            (1, 0, 1, 0),
        ]
        core = ColTableau(2)
        a, _ = core.sample_batch(instrs, [], 500, 20260723)
        b, _ = core.sample_batch(instrs, [], 500, 20260723)

        self.assertEqual(bytes(a), bytes(b), msg="same seed must give the same bytes")

    def test_signed_reset_branch_and_sign(self):
        """
        sample_batch_signed handles OP_RESET branches and carries a signed weight:
        a hand-built {I, -Z, R} table resets the qubit on its R branch and yields
        both signs, mean weight ~ sum(signed weights).
        """
        # X(0) -> |1>, then a signed 1Q channel, then M(0). branch weights sum to 0.9
        # in magnitude 1.1 (gamma); R (opcode 9) resets |1> -> |0>.
        table = [
            (0.9, []),
            (-0.1, [(GATE_OPCODE["Z"], 0, 0)]),
            (0.1, [(9, 0, 0)]),
        ]
        instrs = [
            (0, _X, 0, 0),
            (2, 0, 0, 0),
            (1, 0, 0, 0),
        ]
        core = ColTableau(1)
        buf, weights, num_meas = core.sample_batch_signed(instrs, [table], 20000, 5)
        recs = np.frombuffer(buf, dtype=np.uint8).reshape(20000, num_meas)
        w = np.asarray(weights)

        self.assertEqual(num_meas, 1, msg="one measurement record")

        self.assertTrue(np.any(w < 0.0), msg="the -Z branch must make some weights < 0")

        self.assertTrue(
            np.all(np.isclose(np.abs(w), 1.1)), msg="every |weight| is gamma = 1.1"
        )

        # R resets |1> -> |0>, so some shots read 0 despite the leading X(0)
        self.assertTrue(np.any(recs[:, 0] == 0), msg="the reset branch must zero q0")

        self.assertLess(
            abs(float(w.mean()) - 0.9), 0.05, msg=f"mean weight {w.mean():.3f} ~ 0.9"
        )


if __name__ == "__main__":
    rc = 0
    rc |= Exam("Smoke", "Phase 1 build + import smoke test", "smoke.md").run(
        load(Smoke)
    )
    rc |= Exam("Tableau", "CHP tableau gate correctness", "tableau.md").run(
        load(TableauTests)
    )
    rc |= Exam("Standard", "Textbook stabilizer circuits", "standard.md").run(
        load(StandardTests)
    )
    rc |= Exam("Measure", "Measurement outcomes and statistics", "measure.md").run(
        load(MeasureTests)
    )
    rc |= Exam(
        "Expectation",
        "Pauli expectation values on stabilizer states",
        "expectation.md",
    ).run(load(ExpectationTests))
    rc |= Exam("Pauli", "PauliString parsing and algebra", "pauli.md").run(
        load(PauliTests)
    )
    rc |= Exam("Circuit", "Circuit IR build and run", "circuit.md").run(
        load(CircuitTests)
    )
    rc |= Exam(
        "BatchSampler",
        "Deferred-transpose batched trajectory sampler",
        "batch_sampler.md",
    ).run(load(BatchSamplerTests))
    sys.exit(rc)
