import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from MDR import Exam, Question, load

from aaronson import Simulator
from aaronson.pauli import canonicalize, parse_signed


class TableauTests(Question):
    def _grp(self, sim, *gens):
        """
        Assert the simulator's stabilizer group equals the one generated by gens.
        """
        exp = canonicalize([parse_signed(g) for g in gens], sim.num_qubits)

        self.assertEqual(
            sim.canonical_stabilizers(), exp, msg="stabilizer group mismatch"
        )

    def test_zero_1q(self):
        """
        |0> is stabilized by +Z.
        """
        self._grp(Simulator(1), "+Z")

    def test_zero_3q(self):
        """
        |000> is stabilized by +ZII, +IZI, +IIZ.
        """
        self._grp(Simulator(3), "+ZII", "+IZI", "+IIZ")

    def test_h_plus(self):
        """
        H|0> = |+>, stabilized by +X.
        """
        s = Simulator(1).H(0)
        self._grp(s, "+X")

    def test_s_maps_x_to_y(self):
        """
        S maps X -> Y.
        """
        s = Simulator(1).H(0).S(0)
        self._grp(s, "+Y")

    def test_z_makes_minus(self):
        """
        Z|+> = |->, stabilized by -X.
        """
        s = Simulator(1).H(0).Z(0)
        self._grp(s, "-X")

    def test_y_gate(self):
        """
        Y|0> = i|1>, stabilized by -Z.
        """
        s = Simulator(1).Y(0)
        self._grp(s, "-Z")

    def test_s_dag_inverts_s(self):
        """
        S_DAG . S = identity.
        """
        s = Simulator(1).H(0).S(0).S_DAG(0)
        self._grp(s, "+X")

    def test_bell(self):
        """
        Bell state stabilizers +XX, +ZZ.
        """
        s = Simulator(2).H(0).CX(0, 1)
        self._grp(s, "+XX", "+ZZ")

    def test_ghz(self):
        """
        GHZ_3 group generated by XXX, ZZI, IZZ.
        """
        s = Simulator(3).H(0).CX(0, 1).CX(0, 2)
        self._grp(s, "+XXX", "+ZZI", "+IZZ")

    def test_cz_on_plus(self):
        """
        CZ|++> stabilized by XZ, ZX.
        """
        s = Simulator(2).H(0).H(1).CZ(0, 1)
        self._grp(s, "+XZ", "+ZX")

    def test_swap(self):
        """
        SWAP exchanges |+>|0> -> |0>|+>.
        """
        s = Simulator(2).H(0).SWAP(0, 1)
        self._grp(s, "+ZI", "+IX")

    def test_cx_varargs_pairs(self):
        """
        CX accepts flattened (control, target) pairs.
        """
        s = Simulator(3).H(0).CX(0, 1, 1, 2)  # GHZ via a chain
        self._grp(s, "+XXX", "+ZZI", "+IZZ")

    def test_random_clifford_inverse(self):
        """
        A random Clifford followed by its inverse returns to |0...0>.
        """
        rng = random.Random(7)
        n = 6
        s = Simulator(n)
        ops = []
        for _ in range(120):
            k = rng.random()
            if k < 0.34:
                q = rng.randrange(n)
                s.H(q)
                ops.append(("H", q))
            elif k < 0.67:
                q = rng.randrange(n)
                s.S(q)
                ops.append(("S", q))
            else:
                a = rng.randrange(n)
                b = rng.randrange(n)
                while b == a:
                    b = rng.randrange(n)
                s.CX(a, b)
                ops.append(("CX", a, b))
        for op in reversed(ops):
            if op[0] == "H":
                s.H(op[1])
            elif op[0] == "S":
                s.S_DAG(op[1])
            else:
                s.CX(op[1], op[2])  # CX is its own inverse
        zero = ["+" + "I" * i + "Z" + "I" * (n - 1 - i) for i in range(n)]
        self._grp(s, *zero)


if __name__ == "__main__":
    sys.exit(
        Exam("Tableau", "CHP tableau gate correctness", "tableau.md").run(
            load(TableauTests)
        )
    )
