from __future__ import annotations

import time
from typing import Callable

from ..circuit import Circuit
from ..qec import codes
from ..qec.dem import DetectorErrorModel
from ..qec.threshold import isweep
from .schema import (
    CompileResponse,
    LerPoint,
    RunRequest,
    RunResponse,
)

# Bridge the wire schema to the QEC engine: RunRequest -> Circuit factory ->
# sample/decode/LER. A request carries either a `template` (canonical family +
# distance) or an explicit `spec` (resolved lattice geometry); rounds defaults to
# the code distance (or a small constant for free-form specs).

# wire family name -> codes.* builder function name. The schema's families
# drop the "_code" suffix the engine functions carry.
_FAMILY_BUILDER = {
    "repetition": "repetition_code",
    "rotated_surface": "rotated_surface_code",
    "unrotated_surface": "unrotated_surface_code",
    "toric": "toric_code",
}

# data-qubit count per canonical family at a given distance (for the compile
# summary; the circuits themselves are generated by qliff.qec.codes).
_FAMILY_NUM_DATA = {
    "repetition": lambda d: d,
    "rotated_surface": lambda d: d * d,
    "unrotated_surface": lambda d: d * d + (d - 1) * (d - 1),
    "toric": lambda d: 2 * d * d,
}

_DEFAULT_SPEC_ROUNDS = 3


def _template_circuit_fn(family: str, distance: int, rounds: int) -> Callable:
    """
    codes.<family>(distance, rounds, p) curried over the physical rate p.
    """
    fn_name = _FAMILY_BUILDER.get(family)
    builder = getattr(codes, fn_name, None) if fn_name else None
    if builder is None:
        raise ValueError(f"unknown template family {family!r}")

    return lambda p: builder(distance, rounds, p)


def _spec_circuit_fn(req: RunRequest, rounds: int) -> Callable:
    """
    Free-form LatticeSpec -> lattice.build_circuit(...) curried over p.
    """
    from ..qec import lattice

    spec = req.spec
    boundary = spec.boundary
    channel = req.noise.channel

    if spec.tiles:
        tiles = [t.model_dump() for t in spec.tiles]
        num_data, stabilizers, observables = lattice.resolve_tiles(tiles)
    else:
        num_data = spec.num_data
        stabilizers = [(s.type, s.data) for s in spec.stabilizers]
        observables = [(o.type, o.data) for o in spec.observables]

    return lambda p: lattice.build_circuit(
        num_data,
        stabilizers,
        observables,
        rounds,
        channel,
        p,
        boundary=boundary,
    )


def _rounds(req: RunRequest) -> int:
    """
    Explicit rounds, else the template distance, else a small default.
    """
    if req.rounds is not None:
        return req.rounds

    if req.template is not None:
        return req.template.distance

    return _DEFAULT_SPEC_ROUNDS


def make_circuit_fn(req: RunRequest) -> Callable[[float], Circuit]:
    """
    Build a p -> Circuit factory from a template or an explicit spec.
    """
    rounds = _rounds(req)
    if req.template is not None:
        return _template_circuit_fn(req.template.family, req.template.distance, rounds)

    if req.spec is not None:
        return _spec_circuit_fn(req, rounds)

    raise ValueError("request needs exactly one of template / spec")


def _p_values(req: RunRequest) -> list[float]:
    """
    Resolve the physical-rate sweep: p_sweep if given, else [p], else [0].
    """
    if req.noise.p_sweep:
        return list(req.noise.p_sweep)

    if req.noise.p is not None:
        return [req.noise.p]

    return [0.0]


def _representative_p(req: RunRequest) -> float:
    """
    A single p to build the circuit at for the static compile summary.
    """
    return _p_values(req)[0]


def _resolved_tiles(req: RunRequest) -> tuple[int, list, list]:
    """
    Resolve a free-form tile spec to (num_data, stabilizers, observables), or
    (0, [], []) if it doesn't resolve (e.g. tri/hex tiles, not yet supported).
    """
    from ..qec import lattice

    try:
        tiles = [t.model_dump() for t in req.spec.tiles]

        return lattice.resolve_tiles(tiles)
    except Exception:
        return 0, [], []


def _num_data(req: RunRequest) -> int:
    """
    Data-qubit count from the spec (explicit, or resolved from tiles) or the
    family/distance table (0 if N/A).
    """
    if req.spec is not None:
        if req.spec.num_data is not None:
            return req.spec.num_data

        if req.spec.tiles:
            return _resolved_tiles(req)[0]

    if req.template is not None:
        sizer = _FAMILY_NUM_DATA.get(req.template.family)
        if sizer is not None:
            return sizer(req.template.distance)

    return 0


def _num_stabilizers(req: RunRequest, circuit: Circuit, num_data: int) -> int:
    """
    Stabilizer count from the spec (explicit, or resolved from tiles), else
    inferred ancillas (qubits - data).
    """
    if req.spec is not None:
        if req.spec.stabilizers:
            return len(req.spec.stabilizers)

        if req.spec.tiles:
            return len(_resolved_tiles(req)[1])

    if num_data > 0 and circuit.num_qubits >= num_data:
        return circuit.num_qubits - num_data

    return 0


def compile_summary(req: RunRequest) -> CompileResponse:
    """
    Static circuit summary at a representative p. Never raises: on a bad spec
    it returns ok=False with the error in `warnings`.
    """
    warnings: list[str] = []
    try:
        circuit_fn = make_circuit_fn(req)
        circuit = circuit_fn(_representative_p(req))
    except Exception as exc:  # bad spec / missing builder -> surface as warning
        warnings.append(str(exc))

        return CompileResponse(ok=False, warnings=warnings)

    num_data = _num_data(req)

    return CompileResponse(
        ok=True,
        num_qubits=circuit.num_qubits,
        num_data=num_data,
        num_stabilizers=_num_stabilizers(req, circuit, num_data),
        num_detectors=len(circuit.detectors),
        num_observables=len(circuit.observables),
        warnings=warnings,
    )


def run_sweep(req: RunRequest, on_point=None) -> RunResponse:
    """
    Drive the full LER sweep. Calls on_point(LerPoint) per physical rate (for
    streaming) and returns the complete RunResponse with timing + counts.
    """
    circuit_fn = make_circuit_fn(req)
    p_values = _p_values(req)

    # peek at the first circuit once for qubit / detector counts.
    probe = circuit_fn(p_values[0])
    num_qubits = probe.num_qubits
    num_detectors = len(probe.detectors)

    points: list[LerPoint] = []
    start = time.perf_counter()
    stream = isweep(circuit_fn, p_values, req.decoder, req.shots, req.seed)
    for p, ler, stderr in stream:
        point = LerPoint(p=p, ler=ler, stderr=stderr, shots=req.shots)
        points.append(point)
        if on_point is not None:
            on_point(point)
    elapsed = time.perf_counter() - start

    return RunResponse(
        decoder=req.decoder,
        points=points,
        num_qubits=num_qubits,
        num_detectors=num_detectors,
        elapsed=elapsed,
    )


# kept importable for callers that want a DEM without re-deriving the circuit.
def circuit_dem(circuit: Circuit) -> DetectorErrorModel:
    """
    Convenience: the DetectorErrorModel for an already-built circuit.
    """
    return DetectorErrorModel(circuit)
