import { defineConfig } from 'vitepress';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { svelte } from '@sveltejs/vite-plugin-svelte';

const isDev = process.env.NODE_ENV === 'development';

export default defineConfig({
  base: isDev ? '/' : '/qliff/',
  // Drop a .nojekyll into the build so GitHub Pages serves the output verbatim
  // (Jekyll otherwise skips files/dirs starting with `_`). Written on every build
  // so a fresh `vitepress build` can't wipe it; `gh-pages -t` then publishes it.
  buildEnd: (cfg) => {
    writeFileSync(join(cfg.outDir, '.nojekyll'), '');
  },
  title: "qliff",
  description: "Clifford + noisy stabilizer simulator: a native Rust core with a stim-style uppercase Python API.",
  markdown: {
    math: true,
    lineNumbers: true
  },
  // Test reports under /tests/ are generated by `./do test` and gitignored, so
  // they may be absent on a fresh checkout -- don't fail the build over them.
  ignoreDeadLinks: [/^\/tests\//],
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Getting Started', link: '/getting-started' },
      // Tutorials are now first-class VitePress routes (Svelte explainers mounted
      // as islands inside each markdown page) -- ordinary in-app links.
      { text: 'Tutorials', link: '/tutorials/' },
      { text: 'Examples', link: '/examples/' },
    ],

    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting Started', link: '/getting-started' },
          { text: 'Simulator API', link: '/api' },
          { text: 'Circuit', link: '/circuit' },
          { text: 'Noise', link: '/noise' },
          { text: 'Observables & Metrics', link: '/observables' },
          { text: 'Error Correction', link: '/qec' },
          { text: 'Studio', link: '/studio' },
        ]
      },
      {
        text: 'Examples',
        items: [
          { text: 'Circuits', link: '/examples/circuits' },
          { text: 'Noise', link: '/examples/noise' },
          { text: 'Error Correction', link: '/examples/qec' },
        ],
      },
      {
        // Interactive explainers: Svelte islands mounted into the markdown routes
        // under docs/tutorials/ (source in docs/_tut/). The sidebar order also
        // drives VitePress' native prev/next pager across the seven pages.
        text: 'Tutorials',
        items: [
          { text: 'Overview', link: '/tutorials/' },
          { text: '01 · Gates & CX', link: '/tutorials/gates' },
          { text: '02 · MWPM', link: '/tutorials/mwpm' },
          { text: '03 · Belief propagation', link: '/tutorials/bp' },
          { text: '04 · Tensor networks', link: '/tutorials/tn' },
          { text: '05 · Coherent noise', link: '/tutorials/coherent' },
          { text: '06 · Noise sampling', link: '/tutorials/noise' },
          { text: '07 · Logical error rate', link: '/tutorials/ler' },
        ],
      },
      {
        text: 'Testing',
        items: [
          { text: 'Smoke', link: '/tests/smoke' },
          { text: 'Tableau', link: '/tests/tableau' },
          { text: 'Measure', link: '/tests/measure' },
          { text: 'Expectation', link: '/tests/expectation' },
          { text: 'Pauli', link: '/tests/pauli' },
          { text: 'Standard', link: '/tests/standard' },
          { text: 'Circuit', link: '/tests/circuit' },
          { text: 'Noise', link: '/tests/noise' },
          { text: 'Coherent', link: '/tests/coherent' },
          { text: 'Amplitude', link: '/tests/amplitude' },
          { text: 'Stratified', link: '/tests/stratified' },
          { text: 'Codes', link: '/tests/codes' },
          { text: 'DEM', link: '/tests/dem' },
          { text: 'QEC', link: '/tests/qec' },
        ],
      },
    ],

    search: {
      provider: 'local'
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/plutoniumm/qliff' },
    ]
  },
  vite: {
    plugins: [svelte()],
    resolve: {
      // $lib is how every explainer imports the shared toolkit (Section, Math,
      // colors, ...). Points at docs/_tut/lib.
      alias: {
        $lib: fileURLToPath(new URL('../_tut/lib', import.meta.url)),
      },
    },
    // The explainer modules are imported (not rendered) during the SSR build, so
    // bundle the Svelte runtime + viz libs for that pass instead of externalizing
    // them as bare Node requires.
    ssr: {
      noExternal: ['svelte', 'three', 'uplot', 'katex'],
    },
    server: {
      port: 3000,
      fs: {
        strict: false
      },
    }
  }
});
